default_dependencies: false
build_dependencies:
  - libaio
dependencies:
  - libaio
  - openssl
  - readline
  - libxml2
  - libxslt
  - libevent
targets:
  centos-6:
  centos-7:
env:
  - "LD_LIBRARY_PATH=/tmp/oracle/instantclient_11_1:$LD_LIBRARY_PATH"
  - SKIP_INIT=yes
before_precompile: packaging/before_precompile
after_install: packaging/post_install
